### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by spencershaw** [KodeBlog/Laradmin#2]
I am a noob and first time setting up. Can anyone help getting started?

1. On running composer install the following error returns:
`Script php artisan optimize handling the post-install-cmd event returned with error code 255`

When I go to it fails:
http://localhost/laradmin/public/

PHP error log:
`[03-May-2017 13:38:37 Africa/Dar_es_Salaam] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Unsupported Sentry DSN scheme: <not set>' in C:\wamp64\www\laradmin\vendor\sentry\sentry\lib\Raven\Client.php:311
Stack trace:
#0 C:\wamp64\www\laradmin\vendor\sentry\sentry\lib\Raven\Client.php(61): Raven_Client::parseDSN('null')
#1 C:\wamp64\www\laradmin\vendor\sentry\sentry-laravel\src\Sentry\SentryLaravel\SentryLaravel.php(18): Raven_Client->__construct(Array)
#2 C:\wamp64\www\laradmin\vendor\sentry\sentry-laravel\src\Sentry\SentryLaravel\SentryLaravelServiceProvider.php(87): Sentry\SentryLaravel\SentryLaravel::getClient(Array)
#3 C:\wamp64\www\laradmin\vendor\laravel\framework\src\Illuminate\Container\Container.php(746): Sentry\SentryLaravel\SentryLaravelServiceProvider->Sentry\SentryLaravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 C:\wamp64\www\laradmin\vendor\laravel\framework\src\Illuminate\Container\Container.php(644): Illuminate\Container\Container->build(Object(Closure), Array)
#5 C:\wamp64\www\laradmin\vendor\laravel in C:\wamp64\www\laradmin\vendor\sentry\sentry\lib\Raven\Client.php on line 311`

**Comment by spencershaw** [comment]
Testing on WAMP64 3.06 
PHP 7.0.10 and 5.6.25

**Comment by KodeBlog** [comment]
Hi Spencer. You will have to create an account with https://sentry.io/welcome/ you will be given a sentry DNS that you will have to add to the .env file.

Let me know if you manage to create an account and fix the issue.
